### ISSUE TITLE
discord invite link is invalid

### ISSUE THREAD

**Issue by insanity54** [Rebel459/legacies#1]
Hi thanks for Legacies modpack. I was looking to get started running Legacies on my server but I ran into some errors. I went looking for the discord to see if anybody else ran into the same issue but it looks like the Discord invite link on Modrinth is invalid

![Screenshot_20240208_210408](https://github.com/Rebel459/legacies/assets/670375/0fdb5ba9-1a5e-48e4-a8a4-be034ab71459)

**Comment by Rebel459** [comment]
Ah shit lol, will fix that now thanks :)
Try the page now and you should be good

**Comment by ZZMitch** [comment]
Hey, awesome modpack - going to be playing this for a long time I think! I wanted to check out the Discord as well and post any potential bugs I find - but am getting the same invite invalid screen as above. Thanks!

**Comment by Rebel459** [comment]
Really? That should have been fixed. Appreciate that you’ve been enjoying the pack!

Upon checking, it seems that while i fixed all the links on the page description itself, the integrated link in the left wasn’t updated. It has been fixed now, so thanks for reporting the issue and I look forward to seeing you in the server!
