### ISSUE TITLE
legacies_and_legends:block/empty_texture breaks mipmapping

### ISSUE THREAD

**Issue by pompompopi** [Rebel459/legacies#2]
I'm not sure where I'm supposed to report issues, as it isn't listed on the Legacies and Legends mod page, so I'm opening an issue here. Apologies if this is the wrong place.

# Description

This mod breaks Minecraft's mipmapping functionality. Screenshots on what this looks like below.

# Related Screenshots

## With Legacies and Legends active

![image](https://github.com/Rebel459/legacies/assets/143640209/4a3157e4-d00d-4052-9615-1a057805484c)

## Without Legacies and Legends active (or with the potential solution mentioned below)

![image](https://github.com/Rebel459/legacies/assets/143640209/4fcf1412-fe26-4532-9756-39966840df02)

# Potential Solution

Change the resolution of the `legacies_and_legends:block/empty_texture` texture from 9x9 to 16x16, in line with other Minecraft block textures and other Legacies and Legends block textures.

# Related Logs

```
[20:05:10] [Worker-Main-5/WARN]: Texture legacies_and_legends:block/empty_texture with size 9x9 limits mip level from 4 to 0
[20:05:10] [Worker-Main-5/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1
```

**Comment by Rebel459** [comment]
I believe this issue was fixed in v1.3.6
